name: deploy website
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #  your build commands
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v25 #deploy
        with:
          # vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-token: w4cYqSJ59V03vWUcfuZtKXZo # Required
          # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          # vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-org-id: CvmkL9Dsth5kiYplyJbQK0G8  #Required
          # vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          vercel-project-id: prj_MhCkagc40pxpzHGXEwX1Y5UyUhR8 #Required 
          working-directory: ./sub-directory